CREATE TABLE STATION
(ID INTEGER PRIMARY KEY,
CITY CHAR(20),
STATE CHAR(2),
LAT_N REAL,
LONG_W REAL);

-- populate the table STATION with a few rows:

INSERT INTO STATION VALUES (13, 'Phoenix', 'AZ', 33, 112);
INSERT INTO STATION VALUES (44, 'Denver', 'CO', 40, 105);
INSERT INTO STATION VALUES (66, 'Caribou', 'ME', 47, 68);

SELECT * FROM STATION;

CREATE TABLE STATS
(ID INTEGER REFERENCES STATION(ID),
MONTH INTEGER CHECK (MONTH BETWEEN 1 AND 12),
TEMP_F REAL CHECK (TEMP_F BETWEEN -80 AND 150),
RAIN_I REAL CHECK (RAIN_I BETWEEN 0 AND 100),
PRIMARY KEY (ID, MONTH));

INSERT INTO STATS VALUES (13, 1, 57.4, 0.31);
INSERT INTO STATS VALUES (13, 7, 91.7, 5.15);
INSERT INTO STATS VALUES (44, 1, 27.3, 0.18);
INSERT INTO STATS VALUES (44, 7, 74.8, 2.11);
INSERT INTO STATS VALUES (66, 1, 6.7, 2.10);
INSERT INTO STATS VALUES (66, 7, 65.8, 4.52);
INSERT INTO STATS VALUES (46, 12, 65.8, 4.52);

SELECT * FROM STATS;

SELECT * FROM STATION, STATS
WHERE STATION.ID = STATS.ID;

SELECT MONTH, ID, RAIN_I, TEMP_F
FROM STATS
ORDER BY MONTH,RAIN_I DESC;

SELECT LAT_N, CITY, TEMP_F
FROM STATS, STATION
WHERE MONTH = 7
AND STATS.ID = STATION.ID
ORDER BY TEMP_F;

SELECT MAX(TEMP_F), CAST(MIN(TEMP_F) AS DECIMAL(10,2)), AVG(RAIN_I), ID
FROM STATS
GROUP BY ID;

SELECT * FROM STATION
WHERE 50 < (SELECT AVG(TEMP_F) FROM STATS
WHERE STATION.ID = STATS.ID);

CREATE VIEW METRIC_STATS (ID, MONTH, TEMP_C, RAIN_C) AS
SELECT ID,
MONTH,
(TEMP_F - 32) * 5 /9,
RAIN_I * 0.3937
FROM STATS;

SELECT * FROM METRIC_STATS;

SELECT * FROM METRIC_STATS
WHERE TEMP_C < 0 AND MONTH = 1
ORDER BY RAIN_C;

UPDATE STATS SET RAIN_I = RAIN_I + 0.01;

SELECT * FROM STATS;

UPDATE STATS SET TEMP_F = 74.9
WHERE ID = 44
AND MONTH = 7;

SELECT * FROM STATS;

COMMIT WORK;

UPDATE STATS SET RAIN_I = 4.50
WHERE ID = 44;

SELECT * FROM STATS;

ROLLBACK WORK;

SELECT * FROM STATS;

UPDATE STATS SET RAIN_I = 4.50
WHERE ID = 44
AND MONTH = 7;

COMMIT WORK;

SELECT * FROM STATS;

DELETE FROM STATS
WHERE MONTH = 7
OR ID IN (SELECT ID FROM STATION
WHERE LONG_W < 90);

DELETE FROM STATION WHERE LONG_W < 90;

COMMIT WORK;

SELECT * FROM STATION;

SELECT * FROM STATS;

SELECT * FROM METRIC_STATS;